name: 🐛 Bug Report
description: Report a bug in the modpack
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "### 🐛 Describe the Bug"
  - type: textarea
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "The game crashes when I..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 📷 Screenshots & Logs"
  - type: textarea
    attributes:
      label: "Crash Report or Log"
      description: "If applicable, provide a link to crash report (pastebin, GitHub gist, etc.)."
      placeholder: "Paste the log link here..."
  
  - type: markdown
    attributes:
      value: "### 📌 Steps to Reproduce"
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "How can we reproduce the issue?"
      placeholder: |
        1. Open Minecraft
        2. Join a server
        3. Crash
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Modpack Version"
      description: "Which version of the modpack are you using?"
      options:
        - "Latest"
        - "Older Version (Specify Below)"
    validations:
      required: true

  - type: input
    attributes:
      label: "Minecraft Version"
      description: "Which version of Minecraft?"
      placeholder: "e.g. 1.20.1"

  - type: dropdown
    attributes:
      label: "Launcher Used"
      options:
        - "CurseForge"
        - "Prism Launcher"
        - "MultiMC"
        - "GDLauncher"
        - "Other (Specify Below)"

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Any other relevant information?"

