name: 💡 Feature Request
description: Suggest new mods or features for the modpack
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "### ✨ Feature Description"
  - type: textarea
    attributes:
      label: "What would you like to see?"
      description: "Describe the feature or mod you would like to add."
      placeholder: "I'd like to see a mod that adds..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 🔗 Mod Links (If Any)"
  - type: input
    attributes:
      label: "Mod URL"
      description: "Link to the mod page (CurseForge, Modrinth, etc.)"
      placeholder: "https://modrinth.com/mod/..."

  - type: textarea
    attributes:
      label: "Why is this useful?"
      description: "Explain why this feature would improve the modpack."
  
  - type: dropdown
    attributes:
      label: "Modpack Version"
      options:
        - "Latest"
        - "Older Version (Specify Below)"

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Anything else?"
